/**
 * OZA Design Data
 * Generated from scraped ozadesign.com content
 * DO NOT EDIT MANUALLY - regenerate with: npm run generate-data
 */

import type { Project, Collection, PressItem } from "@/types";

const projects: Project[] = [
  {
    id: "1",
    title: "Cranleigh Lodge",
    slug: "cranleigh-lodge",
    category: "residential",
    location: "London, UK",
    year: 2024,
    status: "completed",
    heroImage: {
      id: "cranleigh-lodge-hero",
      url: "/images/projects/cranleigh-lodge-hero.jpg",
      alt: "Cranleigh Lodge",
      width: 1200,
      height: 800,
    },
    gallery: [
    {
      id: "cranleigh-lodge-gallery-1",
      type: "image",
      url: "/images/projects/cranleigh-lodge-gallery-1.jpg",
      alt: "Cranleigh Lodge - Gallery image 1",
      width: 1200,
      height: 800,
    },
    {
      id: "cranleigh-lodge-gallery-2",
      type: "image",
      url: "/images/projects/cranleigh-lodge-gallery-2.jpg",
      alt: "Cranleigh Lodge - Gallery image 2",
      width: 1200,
      height: 800,
    },
    {
      id: "cranleigh-lodge-gallery-3",
      type: "image",
      url: "/images/projects/cranleigh-lodge-gallery-3.jpg",
      alt: "Cranleigh Lodge - Gallery image 3",
      width: 1200,
      height: 800,
    },
    {
      id: "cranleigh-lodge-video-1",
      type: "video",
      url: "/videos/projects/cranleigh-lodge/video-1.mp4",
      alt: "Cranleigh Lodge - Video 1",
    },
    {
      id: "cranleigh-lodge-gallery-4",
      type: "image",
      url: "/images/projects/cranleigh-lodge-gallery-4.jpg",
      alt: "Cranleigh Lodge - Gallery image 4",
      width: 1200,
      height: 800,
    },
    {
      id: "cranleigh-lodge-gallery-5",
      type: "image",
      url: "/images/projects/cranleigh-lodge-gallery-5.jpg",
      alt: "Cranleigh Lodge - Gallery image 5",
      width: 1200,
      height: 800,
    },
    {
      id: "cranleigh-lodge-gallery-6",
      type: "image",
      url: "/images/projects/cranleigh-lodge-gallery-6.jpg",
      alt: "Cranleigh Lodge - Gallery image 6",
      width: 1200,
      height: 800,
    },
    {
      id: "cranleigh-lodge-gallery-7",
      type: "image",
      url: "/images/projects/cranleigh-lodge-gallery-7.jpg",
      alt: "Cranleigh Lodge - Gallery image 7",
      width: 1200,
      height: 800,
    },
    {
      id: "cranleigh-lodge-gallery-8",
      type: "image",
      url: "/images/projects/cranleigh-lodge-gallery-8.jpg",
      alt: "Cranleigh Lodge - Gallery image 8",
      width: 1200,
      height: 800,
    },
    {
      id: "cranleigh-lodge-gallery-9",
      type: "image",
      url: "/images/projects/cranleigh-lodge-gallery-9.jpg",
      alt: "Cranleigh Lodge - Gallery image 9",
      width: 1200,
      height: 800,
    },
    {
      id: "cranleigh-lodge-gallery-10",
      type: "image",
      url: "/images/projects/cranleigh-lodge-gallery-10.jpg",
      alt: "Cranleigh Lodge - Gallery image 10",
      width: 1200,
      height: 800,
    },
    {
      id: "cranleigh-lodge-gallery-11",
      type: "image",
      url: "/images/projects/cranleigh-lodge-gallery-11.jpg",
      alt: "Cranleigh Lodge - Gallery image 11",
      width: 1200,
      height: 800,
    },
    {
      id: "cranleigh-lodge-gallery-12",
      type: "image",
      url: "/images/projects/cranleigh-lodge-gallery-12.jpg",
      alt: "Cranleigh Lodge - Gallery image 12",
      width: 1200,
      height: 800,
    },
    {
      id: "cranleigh-lodge-gallery-13",
      type: "image",
      url: "/images/projects/cranleigh-lodge-gallery-13.jpg",
      alt: "Cranleigh Lodge - Gallery image 13",
      width: 1200,
      height: 800,
    },
    {
      id: "cranleigh-lodge-gallery-14",
      type: "image",
      url: "/images/projects/cranleigh-lodge-gallery-14.jpg",
      alt: "Cranleigh Lodge - Gallery image 14",
      width: 1200,
      height: 800,
    },
    {
      id: "cranleigh-lodge-gallery-15",
      type: "image",
      url: "/images/projects/cranleigh-lodge-gallery-15.jpg",
      alt: "Cranleigh Lodge - Gallery image 15",
      width: 1200,
      height: 800,
    },
    {
      id: "cranleigh-lodge-gallery-16",
      type: "image",
      url: "/images/projects/cranleigh-lodge-gallery-16.jpg",
      alt: "Cranleigh Lodge - Gallery image 16",
      width: 1200,
      height: 800,
    },
    {
      id: "cranleigh-lodge-gallery-17",
      type: "image",
      url: "/images/projects/cranleigh-lodge-gallery-17.jpg",
      alt: "Cranleigh Lodge - Gallery image 17",
      width: 1200,
      height: 800,
    },
    {
      id: "cranleigh-lodge-gallery-18",
      type: "image",
      url: "/images/projects/cranleigh-lodge-gallery-18.jpg",
      alt: "Cranleigh Lodge - Gallery image 18",
      width: 1200,
      height: 800,
    },
    {
      id: "cranleigh-lodge-gallery-19",
      type: "image",
      url: "/images/projects/cranleigh-lodge-gallery-19.jpg",
      alt: "Cranleigh Lodge - Gallery image 19",
      width: 1200,
      height: 800,
    },
    {
      id: "cranleigh-lodge-gallery-20",
      type: "image",
      url: "/images/projects/cranleigh-lodge-gallery-20.jpg",
      alt: "Cranleigh Lodge - Gallery image 20",
      width: 1200,
      height: 800,
    },
    {
      id: "cranleigh-lodge-gallery-21",
      type: "image",
      url: "/images/projects/cranleigh-lodge-gallery-21.jpg",
      alt: "Cranleigh Lodge - Gallery image 21",
      width: 1200,
      height: 800,
    },
    {
      id: "cranleigh-lodge-gallery-22",
      type: "image",
      url: "/images/projects/cranleigh-lodge-gallery-22.jpg",
      alt: "Cranleigh Lodge - Gallery image 22",
      width: 1200,
      height: 800,
    }
    ],
    description: "In this house, every detail has been designed to distil each project down to the essence, focusing on emphasizing balance and harmony, rather than superficial shine. A peaceful sanctuary feeling and emotional design are applied to the design with ultimate sophisticated detailing.\n\nThe house is invisible from the bustling street, behind a door framed by a distinctive classical stone portal, that was a hidden gem at the heart of Chelsea. As soon as you enter, you are taken to a tranquil oasis, far from the commotion and clamour of the surrounding metropolis.",
    featured: true,
    order: 1,
  },
  {
    id: "2",
    title: "Phi Residential Development",
    slug: "phi-residential-development",
    category: "commercial",
    location: "Istanbul, Turkey",
    year: 2024,
    status: "completed",
    heroImage: {
      id: "phi-residential-development-hero",
      url: "/images/projects/phi-residential-development-hero.jpg",
      alt: "Phi Residential Development",
      width: 1200,
      height: 800,
    },
    gallery: [
    {
      id: "phi-residential-development-gallery-1",
      type: "image",
      url: "/images/projects/phi-residential-development-gallery-1.jpg",
      alt: "Phi Residential Development - Gallery image 1",
      width: 1200,
      height: 800,
    },
    {
      id: "phi-residential-development-gallery-2",
      type: "image",
      url: "/images/projects/phi-residential-development-gallery-2.jpg",
      alt: "Phi Residential Development - Gallery image 2",
      width: 1200,
      height: 800,
    },
    {
      id: "phi-residential-development-gallery-3",
      type: "image",
      url: "/images/projects/phi-residential-development-gallery-3.jpg",
      alt: "Phi Residential Development - Gallery image 3",
      width: 1200,
      height: 800,
    },
    {
      id: "phi-residential-development-video-1",
      type: "video",
      url: "/videos/projects/phi-residential-development/video-1.mp4",
      alt: "Phi Residential Development - Video 1",
    },
    {
      id: "phi-residential-development-gallery-4",
      type: "image",
      url: "/images/projects/phi-residential-development-gallery-4.jpg",
      alt: "Phi Residential Development - Gallery image 4",
      width: 1200,
      height: 800,
    },
    {
      id: "phi-residential-development-gallery-5",
      type: "image",
      url: "/images/projects/phi-residential-development-gallery-5.jpg",
      alt: "Phi Residential Development - Gallery image 5",
      width: 1200,
      height: 800,
    },
    {
      id: "phi-residential-development-gallery-6",
      type: "image",
      url: "/images/projects/phi-residential-development-gallery-6.jpg",
      alt: "Phi Residential Development - Gallery image 6",
      width: 1200,
      height: 800,
    },
    {
      id: "phi-residential-development-gallery-7",
      type: "image",
      url: "/images/projects/phi-residential-development-gallery-7.jpg",
      alt: "Phi Residential Development - Gallery image 7",
      width: 1200,
      height: 800,
    },
    {
      id: "phi-residential-development-gallery-8",
      type: "image",
      url: "/images/projects/phi-residential-development-gallery-8.jpg",
      alt: "Phi Residential Development - Gallery image 8",
      width: 1200,
      height: 800,
    },
    {
      id: "phi-residential-development-gallery-9",
      type: "image",
      url: "/images/projects/phi-residential-development-gallery-9.jpg",
      alt: "Phi Residential Development - Gallery image 9",
      width: 1200,
      height: 800,
    },
    {
      id: "phi-residential-development-gallery-10",
      type: "image",
      url: "/images/projects/phi-residential-development-gallery-10.jpg",
      alt: "Phi Residential Development - Gallery image 10",
      width: 1200,
      height: 800,
    },
    {
      id: "phi-residential-development-gallery-11",
      type: "image",
      url: "/images/projects/phi-residential-development-gallery-11.jpg",
      alt: "Phi Residential Development - Gallery image 11",
      width: 1200,
      height: 800,
    },
    {
      id: "phi-residential-development-gallery-12",
      type: "image",
      url: "/images/projects/phi-residential-development-gallery-12.jpg",
      alt: "Phi Residential Development - Gallery image 12",
      width: 1200,
      height: 800,
    },
    {
      id: "phi-residential-development-gallery-13",
      type: "image",
      url: "/images/projects/phi-residential-development-gallery-13.jpg",
      alt: "Phi Residential Development - Gallery image 13",
      width: 1200,
      height: 800,
    },
    {
      id: "phi-residential-development-gallery-14",
      type: "image",
      url: "/images/projects/phi-residential-development-gallery-14.jpg",
      alt: "Phi Residential Development - Gallery image 14",
      width: 1200,
      height: 800,
    },
    {
      id: "phi-residential-development-gallery-15",
      type: "image",
      url: "/images/projects/phi-residential-development-gallery-15.jpg",
      alt: "Phi Residential Development - Gallery image 15",
      width: 1200,
      height: 800,
    },
    {
      id: "phi-residential-development-gallery-16",
      type: "image",
      url: "/images/projects/phi-residential-development-gallery-16.jpg",
      alt: "Phi Residential Development - Gallery image 16",
      width: 1200,
      height: 800,
    }
    ],
    description: "Located in one of the world’s most incredible places, with historical and geographic significance, comprising the interior design of 6 high-end private residences. A new way of thinking, experiencing, and living the city of the two continents with a blended design of east and west.\n\nAt the crossroad of two continents, Asia and Europe, Istanbul is a megalopolis in perpetual motion and has been fascinating for centuries. Timeless and creative, steeped in history, offering a cultural showcase. You get lost with delight in its heritage, and engage with commercial and popular districts, spread far and wide on either side of the Bosphorus. This city brings together all the intrigues of history, mixing trade culture and a melting pot of peoples, globalisation before its time.",
    featured: true,
    order: 2,
  },
  {
    id: "3",
    title: "Doro Apartment",
    slug: "doro-apartment",
    category: "residential",
    location: "London, UK",
    year: 2024,
    status: "completed",
    heroImage: {
      id: "doro-apartment-hero",
      url: "/images/projects/doro-apartment-hero.jpg",
      alt: "Doro Apartment",
      width: 1200,
      height: 800,
    },
    gallery: [
    {
      id: "doro-apartment-gallery-1",
      type: "image",
      url: "/images/projects/doro-apartment-gallery-1.jpg",
      alt: "Doro Apartment - Gallery image 1",
      width: 1200,
      height: 800,
    },
    {
      id: "doro-apartment-gallery-2",
      type: "image",
      url: "/images/projects/doro-apartment-gallery-2.jpg",
      alt: "Doro Apartment - Gallery image 2",
      width: 1200,
      height: 800,
    },
    {
      id: "doro-apartment-gallery-3",
      type: "image",
      url: "/images/projects/doro-apartment-gallery-3.jpg",
      alt: "Doro Apartment - Gallery image 3",
      width: 1200,
      height: 800,
    },
    {
      id: "doro-apartment-video-1",
      type: "video",
      url: "/videos/projects/doro-apartment/video-1.mp4",
      alt: "Doro Apartment - Video 1",
    },
    {
      id: "doro-apartment-gallery-4",
      type: "image",
      url: "/images/projects/doro-apartment-gallery-4.jpg",
      alt: "Doro Apartment - Gallery image 4",
      width: 1200,
      height: 800,
    },
    {
      id: "doro-apartment-gallery-5",
      type: "image",
      url: "/images/projects/doro-apartment-gallery-5.jpg",
      alt: "Doro Apartment - Gallery image 5",
      width: 1200,
      height: 800,
    },
    {
      id: "doro-apartment-gallery-6",
      type: "image",
      url: "/images/projects/doro-apartment-gallery-6.jpg",
      alt: "Doro Apartment - Gallery image 6",
      width: 1200,
      height: 800,
    },
    {
      id: "doro-apartment-gallery-7",
      type: "image",
      url: "/images/projects/doro-apartment-gallery-7.jpg",
      alt: "Doro Apartment - Gallery image 7",
      width: 1200,
      height: 800,
    },
    {
      id: "doro-apartment-gallery-8",
      type: "image",
      url: "/images/projects/doro-apartment-gallery-8.jpg",
      alt: "Doro Apartment - Gallery image 8",
      width: 1200,
      height: 800,
    },
    {
      id: "doro-apartment-gallery-9",
      type: "image",
      url: "/images/projects/doro-apartment-gallery-9.jpg",
      alt: "Doro Apartment - Gallery image 9",
      width: 1200,
      height: 800,
    },
    {
      id: "doro-apartment-gallery-10",
      type: "image",
      url: "/images/projects/doro-apartment-gallery-10.jpg",
      alt: "Doro Apartment - Gallery image 10",
      width: 1200,
      height: 800,
    },
    {
      id: "doro-apartment-gallery-11",
      type: "image",
      url: "/images/projects/doro-apartment-gallery-11.jpg",
      alt: "Doro Apartment - Gallery image 11",
      width: 1200,
      height: 800,
    }
    ],
    description: "The interior of this typical Victorian style semi-detached house was reinvented for a young couple in the British capital. Built circa 1900, the house features coloured brick and wood, a pitched roof, bay windows and a fireplace in every room which adds instant charm.\n\nIts location in Battersea, South West London, was the main source of inspiration. This is reflected in the kind of living environment created by those who lived during the Industrial Revolution. Our aim was to bring the dark industrial past into the background by designing a house that exudes lightness, calmness and serenity.",
    featured: true,
    order: 3,
  },
  {
    id: "4",
    title: "Richmond Theatre",
    slug: "richmond-theatre",
    category: "cultural",
    location: "London, UK",
    year: 2024,
    status: "completed",
    heroImage: {
      id: "richmond-theatre-hero",
      url: "/images/projects/richmond-theatre-hero.jpg",
      alt: "Richmond Theatre",
      width: 1200,
      height: 800,
    },
    gallery: [
    {
      id: "richmond-theatre-gallery-1",
      type: "image",
      url: "/images/projects/richmond-theatre-gallery-1.jpg",
      alt: "Richmond Theatre - Gallery image 1",
      width: 1200,
      height: 800,
    },
    {
      id: "richmond-theatre-gallery-2",
      type: "image",
      url: "/images/projects/richmond-theatre-gallery-2.jpg",
      alt: "Richmond Theatre - Gallery image 2",
      width: 1200,
      height: 800,
    },
    {
      id: "richmond-theatre-gallery-3",
      type: "image",
      url: "/images/projects/richmond-theatre-gallery-3.jpg",
      alt: "Richmond Theatre - Gallery image 3",
      width: 1200,
      height: 800,
    },
    {
      id: "richmond-theatre-gallery-4",
      type: "image",
      url: "/images/projects/richmond-theatre-gallery-4.jpg",
      alt: "Richmond Theatre - Gallery image 4",
      width: 1200,
      height: 800,
    },
    {
      id: "richmond-theatre-gallery-5",
      type: "image",
      url: "/images/projects/richmond-theatre-gallery-5.jpg",
      alt: "Richmond Theatre - Gallery image 5",
      width: 1200,
      height: 800,
    },
    {
      id: "richmond-theatre-gallery-6",
      type: "image",
      url: "/images/projects/richmond-theatre-gallery-6.jpg",
      alt: "Richmond Theatre - Gallery image 6",
      width: 1200,
      height: 800,
    },
    {
      id: "richmond-theatre-gallery-7",
      type: "image",
      url: "/images/projects/richmond-theatre-gallery-7.jpg",
      alt: "Richmond Theatre - Gallery image 7",
      width: 1200,
      height: 800,
    },
    {
      id: "richmond-theatre-gallery-8",
      type: "image",
      url: "/images/projects/richmond-theatre-gallery-8.jpg",
      alt: "Richmond Theatre - Gallery image 8",
      width: 1200,
      height: 800,
    },
    {
      id: "richmond-theatre-gallery-9",
      type: "image",
      url: "/images/projects/richmond-theatre-gallery-9.jpg",
      alt: "Richmond Theatre - Gallery image 9",
      width: 1200,
      height: 800,
    },
    {
      id: "richmond-theatre-gallery-10",
      type: "image",
      url: "/images/projects/richmond-theatre-gallery-10.jpg",
      alt: "Richmond Theatre - Gallery image 10",
      width: 1200,
      height: 800,
    },
    {
      id: "richmond-theatre-gallery-11",
      type: "image",
      url: "/images/projects/richmond-theatre-gallery-11.jpg",
      alt: "Richmond Theatre - Gallery image 11",
      width: 1200,
      height: 800,
    },
    {
      id: "richmond-theatre-gallery-12",
      type: "image",
      url: "/images/projects/richmond-theatre-gallery-12.jpg",
      alt: "Richmond Theatre - Gallery image 12",
      width: 1200,
      height: 800,
    }
    ],
    description: "Richmond Theatre stands as a testament to the stunning architecture of the late 19th century. It was designed by the renowned theatre architect, Franck Matcham, and opened its doors in 1899.\n\nWith its iconic symmetrical layout and elegant red brick and terra cotta façade, the twin towers with cupolas, baroque centre piece with arched entrance below a scrolled pediment, it has become a Grade II listed building by Historic England. Interestingly, Richmond Theatre is the third theatre to have been built on the site, with the first one opening all the way back in 1718.",
    featured: true,
    order: 4,
  },
  {
    id: "5",
    title: "WOW!house",
    slug: "wow-house",
    category: "cultural",
    location: "Istanbul, Turkey",
    year: 2024,
    status: "completed",
    heroImage: {
      id: "wow-house-hero",
      url: "/images/projects/wow-house-hero.jpg",
      alt: "WOW!house",
      width: 1200,
      height: 800,
    },
    gallery: [
    {
      id: "wow-house-gallery-1",
      type: "image",
      url: "/images/projects/wow-house-gallery-1.jpg",
      alt: "WOW!house - Gallery image 1",
      width: 1200,
      height: 800,
    },
    {
      id: "wow-house-gallery-2",
      type: "image",
      url: "/images/projects/wow-house-gallery-2.jpg",
      alt: "WOW!house - Gallery image 2",
      width: 1200,
      height: 800,
    },
    {
      id: "wow-house-gallery-3",
      type: "image",
      url: "/images/projects/wow-house-gallery-3.jpg",
      alt: "WOW!house - Gallery image 3",
      width: 1200,
      height: 800,
    },
    {
      id: "wow-house-video-1",
      type: "video",
      url: "/videos/projects/wow-house/video-1.mp4",
      alt: "WOW!house - Video 1",
    },
    {
      id: "wow-house-gallery-4",
      type: "image",
      url: "/images/projects/wow-house-gallery-4.jpg",
      alt: "WOW!house - Gallery image 4",
      width: 1200,
      height: 800,
    },
    {
      id: "wow-house-gallery-5",
      type: "image",
      url: "/images/projects/wow-house-gallery-5.jpg",
      alt: "WOW!house - Gallery image 5",
      width: 1200,
      height: 800,
    },
    {
      id: "wow-house-gallery-6",
      type: "image",
      url: "/images/projects/wow-house-gallery-6.jpg",
      alt: "WOW!house - Gallery image 6",
      width: 1200,
      height: 800,
    },
    {
      id: "wow-house-gallery-7",
      type: "image",
      url: "/images/projects/wow-house-gallery-7.jpg",
      alt: "WOW!house - Gallery image 7",
      width: 1200,
      height: 800,
    },
    {
      id: "wow-house-gallery-8",
      type: "image",
      url: "/images/projects/wow-house-gallery-8.jpg",
      alt: "WOW!house - Gallery image 8",
      width: 1200,
      height: 800,
    },
    {
      id: "wow-house-gallery-9",
      type: "image",
      url: "/images/projects/wow-house-gallery-9.jpg",
      alt: "WOW!house - Gallery image 9",
      width: 1200,
      height: 800,
    },
    {
      id: "wow-house-gallery-10",
      type: "image",
      url: "/images/projects/wow-house-gallery-10.jpg",
      alt: "WOW!house - Gallery image 10",
      width: 1200,
      height: 800,
    },
    {
      id: "wow-house-gallery-11",
      type: "image",
      url: "/images/projects/wow-house-gallery-11.jpg",
      alt: "WOW!house - Gallery image 11",
      width: 1200,
      height: 800,
    }
    ],
    description: "We are excited to invite you to explore our capsule space, \"Home Bar by OZA Design,\" at WOW!house 2024.\n\nOur aim was to tell a deeply personal and emotional story through a strong design concept, transporting you to a place where West meets East, mirroring the personal stories of our co-founders. Historically, the Silk Road served as the main conduit connecting these two worlds, with saffron being one of the primary spices traded. Inspired by this, we crafted bespoke colors for the walls using saffron pigments and engaged a remarkable artist to apply textured clay, mimicking the feel of saffron spice—soft and delicate to the touch.",
    featured: true,
    order: 5,
  },
  {
    id: "6",
    title: "Grand Opera House York",
    slug: "grand-opera-house-york",
    category: "cultural",
    location: "London, UK",
    year: 2024,
    status: "completed",
    heroImage: {
      id: "grand-opera-house-york-hero",
      url: "/images/projects/grand-opera-house-york-hero.jpg",
      alt: "Grand Opera House York",
      width: 1200,
      height: 800,
    },
    gallery: [
    {
      id: "grand-opera-house-york-gallery-1",
      type: "image",
      url: "/images/projects/grand-opera-house-york-gallery-1.jpg",
      alt: "Grand Opera House York - Gallery image 1",
      width: 1200,
      height: 800,
    },
    {
      id: "grand-opera-house-york-gallery-2",
      type: "image",
      url: "/images/projects/grand-opera-house-york-gallery-2.jpg",
      alt: "Grand Opera House York - Gallery image 2",
      width: 1200,
      height: 800,
    },
    {
      id: "grand-opera-house-york-gallery-3",
      type: "image",
      url: "/images/projects/grand-opera-house-york-gallery-3.jpg",
      alt: "Grand Opera House York - Gallery image 3",
      width: 1200,
      height: 800,
    },
    {
      id: "grand-opera-house-york-gallery-4",
      type: "image",
      url: "/images/projects/grand-opera-house-york-gallery-4.jpg",
      alt: "Grand Opera House York - Gallery image 4",
      width: 1200,
      height: 800,
    },
    {
      id: "grand-opera-house-york-gallery-5",
      type: "image",
      url: "/images/projects/grand-opera-house-york-gallery-5.jpg",
      alt: "Grand Opera House York - Gallery image 5",
      width: 1200,
      height: 800,
    },
    {
      id: "grand-opera-house-york-gallery-6",
      type: "image",
      url: "/images/projects/grand-opera-house-york-gallery-6.jpg",
      alt: "Grand Opera House York - Gallery image 6",
      width: 1200,
      height: 800,
    },
    {
      id: "grand-opera-house-york-gallery-7",
      type: "image",
      url: "/images/projects/grand-opera-house-york-gallery-7.jpg",
      alt: "Grand Opera House York - Gallery image 7",
      width: 1200,
      height: 800,
    },
    {
      id: "grand-opera-house-york-gallery-8",
      type: "image",
      url: "/images/projects/grand-opera-house-york-gallery-8.jpg",
      alt: "Grand Opera House York - Gallery image 8",
      width: 1200,
      height: 800,
    },
    {
      id: "grand-opera-house-york-gallery-9",
      type: "image",
      url: "/images/projects/grand-opera-house-york-gallery-9.jpg",
      alt: "Grand Opera House York - Gallery image 9",
      width: 1200,
      height: 800,
    },
    {
      id: "grand-opera-house-york-gallery-10",
      type: "image",
      url: "/images/projects/grand-opera-house-york-gallery-10.jpg",
      alt: "Grand Opera House York - Gallery image 10",
      width: 1200,
      height: 800,
    },
    {
      id: "grand-opera-house-york-gallery-11",
      type: "image",
      url: "/images/projects/grand-opera-house-york-gallery-11.jpg",
      alt: "Grand Opera House York - Gallery image 11",
      width: 1200,
      height: 800,
    },
    {
      id: "grand-opera-house-york-gallery-12",
      type: "image",
      url: "/images/projects/grand-opera-house-york-gallery-12.jpg",
      alt: "Grand Opera House York - Gallery image 12",
      width: 1200,
      height: 800,
    }
    ],
    description: "The Grand Opera House in York is a stunning building with a fascinating history. Originally constructed in 1868 as a Corn Exchange and Warehouse, it was later transformed into a theatre in 1902. However, in 1958, the stalls boxes and stage were removed, and the space was repurposed for roller-skating, dance, bingo, and wrestling. It was renamed as the SS Empire, and it remained this way for almost thirty years. Fortunately, in 1987, the theatre was finally restored to its original function and design, providing audiences with an exceptional theatrical experience.\n\nŌZA had the honour of being selected as the interior designer for the Grand Opera House York renovation. The main auditorium, foyer, bar, as well as the places where performers get ready for performances, like dressing rooms and bathrooms, were all upgraded by our team. Our main objective was to respect the theater's rich history and bring back its distinctive character to its former splendour.",
    featured: true,
    order: 6,
  },
  {
    id: "7",
    title: "Ioa Villa",
    slug: "ioa-villa",
    category: "residential",
    location: "London, UK",
    year: 2023,
    status: "completed",
    heroImage: {
      id: "ioa-villa-hero",
      url: "/images/projects/ioa-villa-hero.jpg",
      alt: "Ioa Villa",
      width: 1200,
      height: 800,
    },
    gallery: [
    {
      id: "ioa-villa-gallery-1",
      type: "image",
      url: "/images/projects/ioa-villa-gallery-1.jpg",
      alt: "Ioa Villa - Gallery image 1",
      width: 1200,
      height: 800,
    },
    {
      id: "ioa-villa-gallery-2",
      type: "image",
      url: "/images/projects/ioa-villa-gallery-2.jpg",
      alt: "Ioa Villa - Gallery image 2",
      width: 1200,
      height: 800,
    },
    {
      id: "ioa-villa-gallery-3",
      type: "image",
      url: "/images/projects/ioa-villa-gallery-3.jpg",
      alt: "Ioa Villa - Gallery image 3",
      width: 1200,
      height: 800,
    },
    {
      id: "ioa-villa-video-1",
      type: "video",
      url: "/videos/projects/ioa-villa/video-1.mp4",
      alt: "Ioa Villa - Video 1",
    },
    {
      id: "ioa-villa-gallery-4",
      type: "image",
      url: "/images/projects/ioa-villa-gallery-4.jpg",
      alt: "Ioa Villa - Gallery image 4",
      width: 1200,
      height: 800,
    },
    {
      id: "ioa-villa-gallery-5",
      type: "image",
      url: "/images/projects/ioa-villa-gallery-5.jpg",
      alt: "Ioa Villa - Gallery image 5",
      width: 1200,
      height: 800,
    },
    {
      id: "ioa-villa-gallery-6",
      type: "image",
      url: "/images/projects/ioa-villa-gallery-6.jpg",
      alt: "Ioa Villa - Gallery image 6",
      width: 1200,
      height: 800,
    },
    {
      id: "ioa-villa-gallery-7",
      type: "image",
      url: "/images/projects/ioa-villa-gallery-7.jpg",
      alt: "Ioa Villa - Gallery image 7",
      width: 1200,
      height: 800,
    },
    {
      id: "ioa-villa-gallery-8",
      type: "image",
      url: "/images/projects/ioa-villa-gallery-8.jpg",
      alt: "Ioa Villa - Gallery image 8",
      width: 1200,
      height: 800,
    },
    {
      id: "ioa-villa-gallery-9",
      type: "image",
      url: "/images/projects/ioa-villa-gallery-9.jpg",
      alt: "Ioa Villa - Gallery image 9",
      width: 1200,
      height: 800,
    }
    ],
    description: "Located on the west coast of Türkiye, IOA Villa is built on land surrounded by the Aegean Sea and a forest. Opening onto this forest, each room features a spectacular natural view from the main patio.\n\nCarefully designed circulations offer soft transitions between the social and private areas through seamless connections between interior and exterior spaces.",
    featured: false,
    order: 7,
  },
  {
    id: "8",
    title: "Era House",
    slug: "era-house",
    category: "residential",
    location: "London, UK",
    year: 2023,
    status: "completed",
    heroImage: {
      id: "era-house-hero",
      url: "/images/projects/era-house-hero.jpg",
      alt: "Era House",
      width: 1200,
      height: 800,
    },
    gallery: [
    {
      id: "era-house-gallery-1",
      type: "image",
      url: "/images/projects/era-house-gallery-1.jpg",
      alt: "Era House - Gallery image 1",
      width: 1200,
      height: 800,
    },
    {
      id: "era-house-gallery-2",
      type: "image",
      url: "/images/projects/era-house-gallery-2.jpg",
      alt: "Era House - Gallery image 2",
      width: 1200,
      height: 800,
    },
    {
      id: "era-house-gallery-3",
      type: "image",
      url: "/images/projects/era-house-gallery-3.jpg",
      alt: "Era House - Gallery image 3",
      width: 1200,
      height: 800,
    },
    {
      id: "era-house-video-1",
      type: "video",
      url: "/videos/projects/era-house/video-1.mp4",
      alt: "Era House - Video 1",
    },
    {
      id: "era-house-gallery-4",
      type: "image",
      url: "/images/projects/era-house-gallery-4.jpg",
      alt: "Era House - Gallery image 4",
      width: 1200,
      height: 800,
    },
    {
      id: "era-house-gallery-5",
      type: "image",
      url: "/images/projects/era-house-gallery-5.jpg",
      alt: "Era House - Gallery image 5",
      width: 1200,
      height: 800,
    },
    {
      id: "era-house-gallery-6",
      type: "image",
      url: "/images/projects/era-house-gallery-6.jpg",
      alt: "Era House - Gallery image 6",
      width: 1200,
      height: 800,
    },
    {
      id: "era-house-gallery-7",
      type: "image",
      url: "/images/projects/era-house-gallery-7.jpg",
      alt: "Era House - Gallery image 7",
      width: 1200,
      height: 800,
    }
    ],
    description: "In response to the owners’ unique contemporary tastes and initial brief specification, this house boasts a spacious interior and masculine, monochromatic aesthetic.\n\nWith understated decor and natural materials, such as clay and raw timber, the house combines a minimalist aesthetic of elegance combined with effortless sophistication.",
    featured: false,
    order: 8,
  },
  {
    id: "9",
    title: "Arena 42 Art Gallery",
    slug: "arena-42-art-gallery",
    category: "residential",
    location: "London, UK",
    year: 2023,
    status: "completed",
    heroImage: {
      id: "arena-42-art-gallery-hero",
      url: "/images/projects/arena-42-art-gallery-hero.jpg",
      alt: "Arena 42 Art Gallery",
      width: 1200,
      height: 800,
    },
    gallery: [
    {
      id: "arena-42-art-gallery-gallery-1",
      type: "image",
      url: "/images/projects/arena-42-art-gallery-gallery-1.jpg",
      alt: "Arena 42 Art Gallery - Gallery image 1",
      width: 1200,
      height: 800,
    },
    {
      id: "arena-42-art-gallery-gallery-2",
      type: "image",
      url: "/images/projects/arena-42-art-gallery-gallery-2.jpg",
      alt: "Arena 42 Art Gallery - Gallery image 2",
      width: 1200,
      height: 800,
    },
    {
      id: "arena-42-art-gallery-gallery-3",
      type: "image",
      url: "/images/projects/arena-42-art-gallery-gallery-3.jpg",
      alt: "Arena 42 Art Gallery - Gallery image 3",
      width: 1200,
      height: 800,
    },
    {
      id: "arena-42-art-gallery-video-1",
      type: "video",
      url: "/videos/projects/arena-42-art-gallery/video-1.mp4",
      alt: "Arena 42 Art Gallery - Video 1",
    },
    {
      id: "arena-42-art-gallery-gallery-4",
      type: "image",
      url: "/images/projects/arena-42-art-gallery-gallery-4.jpg",
      alt: "Arena 42 Art Gallery - Gallery image 4",
      width: 1200,
      height: 800,
    },
    {
      id: "arena-42-art-gallery-gallery-5",
      type: "image",
      url: "/images/projects/arena-42-art-gallery-gallery-5.jpg",
      alt: "Arena 42 Art Gallery - Gallery image 5",
      width: 1200,
      height: 800,
    },
    {
      id: "arena-42-art-gallery-gallery-6",
      type: "image",
      url: "/images/projects/arena-42-art-gallery-gallery-6.jpg",
      alt: "Arena 42 Art Gallery - Gallery image 6",
      width: 1200,
      height: 800,
    },
    {
      id: "arena-42-art-gallery-gallery-7",
      type: "image",
      url: "/images/projects/arena-42-art-gallery-gallery-7.jpg",
      alt: "Arena 42 Art Gallery - Gallery image 7",
      width: 1200,
      height: 800,
    },
    {
      id: "arena-42-art-gallery-gallery-8",
      type: "image",
      url: "/images/projects/arena-42-art-gallery-gallery-8.jpg",
      alt: "Arena 42 Art Gallery - Gallery image 8",
      width: 1200,
      height: 800,
    }
    ],
    description: "We were approached by an art gallery to rethink and redesign their existing space. In response to the monolithic and contemporary initial brief, this project offers a theatrical interior and a unique monochromatic appearance.\n\nFunctioning both as a store and a gallery, this space immerses visitors in a sculptural sanctuary. It is characterised by a modern, clean-cut, radical aesthetic that promotes spirituality and fosters conversations on temporary exhibitions.",
    featured: false,
    order: 9,
  },
  {
    id: "10",
    title: "Ela House",
    slug: "ela-house",
    category: "residential",
    location: "London, UK",
    year: 2023,
    status: "completed",
    heroImage: {
      id: "ela-house-hero",
      url: "",
      alt: "Ela House",
      width: 1200,
      height: 800,
    },
    gallery: [
    
    ],
    description: "",
    featured: false,
    order: 10,
  },
  {
    id: "11",
    title: "Ammon House",
    slug: "ammon-house",
    category: "residential",
    location: "London, UK",
    year: 2023,
    status: "completed",
    heroImage: {
      id: "ammon-house-hero",
      url: "",
      alt: "Ammon House",
      width: 1200,
      height: 800,
    },
    gallery: [
    
    ],
    description: "",
    featured: false,
    order: 11,
  }
];

const collections: Collection[] = [
  {
    id: "1",
    title: "Sofa",
    slug: "sofa",
    heroImage: {
      id: "sofa-hero",
      url: "/images/collections/sofa-heracles-sofa-1.jpg",
      alt: "Sofa",
      width: 1200,
      height: 800,
    },
    products: [
      {
        id: "sofa-product-1",
        name: "Heracles Sofa",
        collectionName: "Warrior Collection",
        images: [
        {
      id: "sofa-heracles-sofa-1",
      url: "/images/collections/sofa-heracles-sofa-1.jpg",
      alt: "Heracles Sofa - Image 1",
      width: 1200,
      height: 800,
    },
        {
      id: "sofa-heracles-sofa-2",
      url: "/images/collections/sofa-heracles-sofa-2.jpg",
      alt: "Heracles Sofa - Image 2",
      width: 1200,
      height: 800,
    },
        {
      id: "sofa-heracles-sofa-3",
      url: "/images/collections/sofa-heracles-sofa-3.jpg",
      alt: "Heracles Sofa - Image 3",
      width: 1200,
      height: 800,
    },
        {
      id: "sofa-heracles-sofa-4",
      url: "/images/collections/sofa-heracles-sofa-4.jpg",
      alt: "Heracles Sofa - Image 4",
      width: 1200,
      height: 800,
    },
        {
      id: "sofa-heracles-sofa-5",
      url: "/images/collections/sofa-heracles-sofa-5.jpg",
      alt: "Heracles Sofa - Image 5",
      width: 1200,
      height: 800,
    },
        {
      id: "sofa-heracles-sofa-6",
      url: "/images/collections/sofa-heracles-sofa-6.jpg",
      alt: "Heracles Sofa - Image 6",
      width: 1200,
      height: 800,
    }
        ],
        materials: "Wooden frame with upholstered seating, cushions and patinated bronze details",
        dimensions: ["2000w x 900d x 650h  mm", "2200w x 900d x 650h  mm"],
        order: 1,
      },
      {
        id: "sofa-product-2",
        name: "Odysseus Sofa",
        collectionName: "Warrior Collection",
        images: [
        {
      id: "sofa-odysseus-sofa-1",
      url: "/images/collections/sofa-odysseus-sofa-1.jpg",
      alt: "Odysseus Sofa - Image 1",
      width: 1200,
      height: 800,
    },
        {
      id: "sofa-odysseus-sofa-2",
      url: "/images/collections/sofa-odysseus-sofa-2.jpg",
      alt: "Odysseus Sofa - Image 2",
      width: 1200,
      height: 800,
    },
        {
      id: "sofa-odysseus-sofa-3",
      url: "/images/collections/sofa-odysseus-sofa-3.jpg",
      alt: "Odysseus Sofa - Image 3",
      width: 1200,
      height: 800,
    },
        {
      id: "sofa-odysseus-sofa-4",
      url: "/images/collections/sofa-odysseus-sofa-4.jpg",
      alt: "Odysseus Sofa - Image 4",
      width: 1200,
      height: 800,
    },
        {
      id: "sofa-odysseus-sofa-5",
      url: "/images/collections/sofa-odysseus-sofa-5.jpg",
      alt: "Odysseus Sofa - Image 5",
      width: 1200,
      height: 800,
    },
        {
      id: "sofa-odysseus-sofa-6",
      url: "/images/collections/sofa-odysseus-sofa-6.jpg",
      alt: "Odysseus Sofa - Image 6",
      width: 1200,
      height: 800,
    }
        ],
        materials: "Fully upholstered sofa with cushions",
        dimensions: ["2600w x 1120d x 670h  mm", "2800w x 1120d x 670h  mm"],
        order: 2,
      }
    ],
    order: 1,
  },
  {
    id: "2",
    title: "Bench",
    slug: "bench",
    heroImage: {
      id: "bench-hero",
      url: "/images/collections/bench-bellerophon-bench-1.jpg",
      alt: "Bench",
      width: 1200,
      height: 800,
    },
    products: [
      {
        id: "bench-product-1",
        name: "Bellerophon Bench",
        collectionName: "Warrior Collection",
        images: [
        {
      id: "bench-bellerophon-bench-1",
      url: "/images/collections/bench-bellerophon-bench-1.jpg",
      alt: "Bellerophon Bench - Image 1",
      width: 1200,
      height: 800,
    },
        {
      id: "bench-bellerophon-bench-2",
      url: "/images/collections/bench-bellerophon-bench-2.jpg",
      alt: "Bellerophon Bench - Image 2",
      width: 1200,
      height: 800,
    },
        {
      id: "bench-bellerophon-bench-3",
      url: "/images/collections/bench-bellerophon-bench-3.jpg",
      alt: "Bellerophon Bench - Image 3",
      width: 1200,
      height: 800,
    },
        {
      id: "bench-bellerophon-bench-4",
      url: "/images/collections/bench-bellerophon-bench-4.jpg",
      alt: "Bellerophon Bench - Image 4",
      width: 1200,
      height: 800,
    },
        {
      id: "bench-bellerophon-bench-5",
      url: "/images/collections/bench-bellerophon-bench-5.jpg",
      alt: "Bellerophon Bench - Image 5",
      width: 1200,
      height: 800,
    }
        ],
        materials: "Wooden frame with upholstered seating and patinated bronze detailing",
        dimensions: ["1500w x 450d x 450h mm", "1730w x 450d x 450h mm"],
        order: 1,
      }
    ],
    order: 2,
  },
  {
    id: "3",
    title: "Lounge Chair",
    slug: "lounge-chair",
    heroImage: {
      id: "lounge-chair-hero",
      url: "/images/collections/lounge-chair-aeneas-lounge-chair-1.jpg",
      alt: "Lounge Chair",
      width: 1200,
      height: 800,
    },
    products: [
      {
        id: "lounge-chair-product-1",
        name: "Aeneas Lounge Chair",
        collectionName: "Warrior Collection",
        images: [
        {
      id: "lounge-chair-aeneas-lounge-chair-1",
      url: "/images/collections/lounge-chair-aeneas-lounge-chair-1.jpg",
      alt: "Aeneas Lounge Chair - Image 1",
      width: 1200,
      height: 800,
    },
        {
      id: "lounge-chair-aeneas-lounge-chair-2",
      url: "/images/collections/lounge-chair-aeneas-lounge-chair-2.jpg",
      alt: "Aeneas Lounge Chair - Image 2",
      width: 1200,
      height: 800,
    },
        {
      id: "lounge-chair-aeneas-lounge-chair-3",
      url: "/images/collections/lounge-chair-aeneas-lounge-chair-3.jpg",
      alt: "Aeneas Lounge Chair - Image 3",
      width: 1200,
      height: 800,
    },
        {
      id: "lounge-chair-aeneas-lounge-chair-4",
      url: "/images/collections/lounge-chair-aeneas-lounge-chair-4.jpg",
      alt: "Aeneas Lounge Chair - Image 4",
      width: 1200,
      height: 800,
    },
        {
      id: "lounge-chair-aeneas-lounge-chair-5",
      url: "/images/collections/lounge-chair-aeneas-lounge-chair-5.jpg",
      alt: "Aeneas Lounge Chair - Image 5",
      width: 1200,
      height: 800,
    },
        {
      id: "lounge-chair-aeneas-lounge-chair-6",
      url: "/images/collections/lounge-chair-aeneas-lounge-chair-6.jpg",
      alt: "Aeneas Lounge Chair - Image 6",
      width: 1200,
      height: 800,
    }
        ],
        materials: "Wooden frame with upholstered seating and patinated bronze trims",
        dimensions: ["640w x 572d x 752h mm"],
        order: 1,
      },
      {
        id: "lounge-chair-product-2",
        name: "Hector Lounge Chair",
        collectionName: "Warrior Collection",
        images: [
        {
      id: "lounge-chair-hector-lounge-chair-1",
      url: "/images/collections/lounge-chair-hector-lounge-chair-1.jpg",
      alt: "Hector Lounge Chair - Image 1",
      width: 1200,
      height: 800,
    },
        {
      id: "lounge-chair-hector-lounge-chair-2",
      url: "/images/collections/lounge-chair-hector-lounge-chair-2.jpg",
      alt: "Hector Lounge Chair - Image 2",
      width: 1200,
      height: 800,
    },
        {
      id: "lounge-chair-hector-lounge-chair-3",
      url: "/images/collections/lounge-chair-hector-lounge-chair-3.jpg",
      alt: "Hector Lounge Chair - Image 3",
      width: 1200,
      height: 800,
    },
        {
      id: "lounge-chair-hector-lounge-chair-4",
      url: "/images/collections/lounge-chair-hector-lounge-chair-4.jpg",
      alt: "Hector Lounge Chair - Image 4",
      width: 1200,
      height: 800,
    },
        {
      id: "lounge-chair-hector-lounge-chair-5",
      url: "/images/collections/lounge-chair-hector-lounge-chair-5.jpg",
      alt: "Hector Lounge Chair - Image 5",
      width: 1200,
      height: 800,
    },
        {
      id: "lounge-chair-hector-lounge-chair-6",
      url: "/images/collections/lounge-chair-hector-lounge-chair-6.jpg",
      alt: "Hector Lounge Chair - Image 6",
      width: 1200,
      height: 800,
    }
        ],
        materials: "Wooden frame with upholstered seating",
        dimensions: ["800w x 880d x 670h  mm"],
        order: 2,
      }
    ],
    order: 3,
  },
  {
    id: "4",
    title: "Console",
    slug: "console",
    heroImage: {
      id: "console-hero",
      url: "/images/collections/console-achilles-console-1.jpg",
      alt: "Console",
      width: 1200,
      height: 800,
    },
    products: [
      {
        id: "console-product-1",
        name: "Achilles Console",
        collectionName: "Warrior Collection",
        images: [
        {
      id: "console-achilles-console-1",
      url: "/images/collections/console-achilles-console-1.jpg",
      alt: "Achilles Console - Image 1",
      width: 1200,
      height: 800,
    },
        {
      id: "console-achilles-console-2",
      url: "/images/collections/console-achilles-console-2.jpg",
      alt: "Achilles Console - Image 2",
      width: 1200,
      height: 800,
    },
        {
      id: "console-achilles-console-3",
      url: "/images/collections/console-achilles-console-3.jpg",
      alt: "Achilles Console - Image 3",
      width: 1200,
      height: 800,
    },
        {
      id: "console-achilles-console-4",
      url: "/images/collections/console-achilles-console-4.jpg",
      alt: "Achilles Console - Image 4",
      width: 1200,
      height: 800,
    },
        {
      id: "console-achilles-console-5",
      url: "/images/collections/console-achilles-console-5.jpg",
      alt: "Achilles Console - Image 5",
      width: 1200,
      height: 800,
    }
        ],
        materials: "Wooden base and table top",
        dimensions: ["1400w x 450d x 801h mm", "1600w x 450d x 801h mm"],
        order: 1,
      },
      {
        id: "console-product-2",
        name: "Ares Console",
        collectionName: "Warrior Collection",
        images: [
        {
      id: "console-ares-console-1",
      url: "/images/collections/console-ares-console-1.jpg",
      alt: "Ares Console - Image 1",
      width: 1200,
      height: 800,
    },
        {
      id: "console-ares-console-2",
      url: "/images/collections/console-ares-console-2.jpg",
      alt: "Ares Console - Image 2",
      width: 1200,
      height: 800,
    },
        {
      id: "console-ares-console-3",
      url: "/images/collections/console-ares-console-3.jpg",
      alt: "Ares Console - Image 3",
      width: 1200,
      height: 800,
    },
        {
      id: "console-ares-console-4",
      url: "/images/collections/console-ares-console-4.jpg",
      alt: "Ares Console - Image 4",
      width: 1200,
      height: 800,
    },
        {
      id: "console-ares-console-5",
      url: "/images/collections/console-ares-console-5.jpg",
      alt: "Ares Console - Image 5",
      width: 1200,
      height: 800,
    }
        ],
        materials: "Black patinated cast bronze base with marble top",
        dimensions: ["1830w x 430d x 750h mm"],
        order: 2,
      }
    ],
    order: 4,
  },
  {
    id: "5",
    title: "Daybed",
    slug: "daybed",
    heroImage: {
      id: "daybed-hero",
      url: "/images/collections/daybed-athena-daybed-1.jpg",
      alt: "Daybed",
      width: 1200,
      height: 800,
    },
    products: [
      {
        id: "daybed-product-1",
        name: "Athena Daybed",
        collectionName: "Warrior Collection",
        images: [
        {
      id: "daybed-athena-daybed-1",
      url: "/images/collections/daybed-athena-daybed-1.jpg",
      alt: "Athena Daybed - Image 1",
      width: 1200,
      height: 800,
    },
        {
      id: "daybed-athena-daybed-2",
      url: "/images/collections/daybed-athena-daybed-2.jpg",
      alt: "Athena Daybed - Image 2",
      width: 1200,
      height: 800,
    },
        {
      id: "daybed-athena-daybed-3",
      url: "/images/collections/daybed-athena-daybed-3.jpg",
      alt: "Athena Daybed - Image 3",
      width: 1200,
      height: 800,
    },
        {
      id: "daybed-athena-daybed-4",
      url: "/images/collections/daybed-athena-daybed-4.jpg",
      alt: "Athena Daybed - Image 4",
      width: 1200,
      height: 800,
    },
        {
      id: "daybed-athena-daybed-5",
      url: "/images/collections/daybed-athena-daybed-5.jpg",
      alt: "Athena Daybed - Image 5",
      width: 1200,
      height: 800,
    },
        {
      id: "daybed-athena-daybed-6",
      url: "/images/collections/daybed-athena-daybed-6.jpg",
      alt: "Athena Daybed - Image 6",
      width: 1200,
      height: 800,
    }
        ],
        materials: "Wooden and metal base with upholstered seating and cushion",
        dimensions: ["2000w x 800d x 440h mm"],
        order: 1,
      }
    ],
    order: 5,
  },
  {
    id: "6",
    title: "Dining Table",
    slug: "dining-table",
    heroImage: {
      id: "dining-table-hero",
      url: "/images/collections/dining-table-theseus-dining-table-1.jpg",
      alt: "Dining Table",
      width: 1200,
      height: 800,
    },
    products: [
      {
        id: "dining-table-product-1",
        name: "Theseus Dining Table",
        collectionName: "Warrior Collection",
        images: [
        {
      id: "dining-table-theseus-dining-table-1",
      url: "/images/collections/dining-table-theseus-dining-table-1.jpg",
      alt: "Theseus Dining Table - Image 1",
      width: 1200,
      height: 800,
    },
        {
      id: "dining-table-theseus-dining-table-2",
      url: "/images/collections/dining-table-theseus-dining-table-2.jpg",
      alt: "Theseus Dining Table - Image 2",
      width: 1200,
      height: 800,
    },
        {
      id: "dining-table-theseus-dining-table-3",
      url: "/images/collections/dining-table-theseus-dining-table-3.jpg",
      alt: "Theseus Dining Table - Image 3",
      width: 1200,
      height: 800,
    },
        {
      id: "dining-table-theseus-dining-table-4",
      url: "/images/collections/dining-table-theseus-dining-table-4.jpg",
      alt: "Theseus Dining Table - Image 4",
      width: 1200,
      height: 800,
    },
        {
      id: "dining-table-theseus-dining-table-5",
      url: "/images/collections/dining-table-theseus-dining-table-5.jpg",
      alt: "Theseus Dining Table - Image 5",
      width: 1200,
      height: 800,
    }
        ],
        materials: "Wooden base and table top",
        dimensions: ["2300w x 1000d x 740h mm", "3000w x 1100d x 740h mm"],
        order: 1,
      }
    ],
    order: 6,
  },
  {
    id: "7",
    title: "Coffee Table",
    slug: "coffee-table",
    heroImage: {
      id: "coffee-table-hero",
      url: "/images/collections/coffee-table-enyo-coffee-table-1.jpg",
      alt: "Coffee Table",
      width: 1200,
      height: 800,
    },
    products: [
      {
        id: "coffee-table-product-1",
        name: "Enyo Coffee Table",
        collectionName: "Warrior Collection",
        images: [
        {
      id: "coffee-table-enyo-coffee-table-1",
      url: "/images/collections/coffee-table-enyo-coffee-table-1.jpg",
      alt: "Enyo Coffee Table - Image 1",
      width: 1200,
      height: 800,
    },
        {
      id: "coffee-table-enyo-coffee-table-2",
      url: "/images/collections/coffee-table-enyo-coffee-table-2.jpg",
      alt: "Enyo Coffee Table - Image 2",
      width: 1200,
      height: 800,
    },
        {
      id: "coffee-table-enyo-coffee-table-3",
      url: "/images/collections/coffee-table-enyo-coffee-table-3.jpg",
      alt: "Enyo Coffee Table - Image 3",
      width: 1200,
      height: 800,
    },
        {
      id: "coffee-table-enyo-coffee-table-4",
      url: "/images/collections/coffee-table-enyo-coffee-table-4.jpg",
      alt: "Enyo Coffee Table - Image 4",
      width: 1200,
      height: 800,
    },
        {
      id: "coffee-table-enyo-coffee-table-5",
      url: "/images/collections/coffee-table-enyo-coffee-table-5.jpg",
      alt: "Enyo Coffee Table - Image 5",
      width: 1200,
      height: 800,
    }
        ],
        materials: "Patinated brass table top with travertine base",
        dimensions: ["1600w x 900d x 350h mm", "2000w x 900d x 350h mm"],
        order: 1,
      }
    ],
    order: 7,
  },
  {
    id: "8",
    title: "Side Table",
    slug: "side-table",
    heroImage: {
      id: "side-table-hero",
      url: "/images/collections/side-table-perseus-side-table-1.jpg",
      alt: "Side Table",
      width: 1200,
      height: 800,
    },
    products: [
      {
        id: "side-table-product-1",
        name: "Perseus Side Table",
        collectionName: "Warrior Collection",
        images: [
        {
      id: "side-table-perseus-side-table-1",
      url: "/images/collections/side-table-perseus-side-table-1.jpg",
      alt: "Perseus Side Table - Image 1",
      width: 1200,
      height: 800,
    },
        {
      id: "side-table-perseus-side-table-2",
      url: "/images/collections/side-table-perseus-side-table-2.jpg",
      alt: "Perseus Side Table - Image 2",
      width: 1200,
      height: 800,
    },
        {
      id: "side-table-perseus-side-table-3",
      url: "/images/collections/side-table-perseus-side-table-3.jpg",
      alt: "Perseus Side Table - Image 3",
      width: 1200,
      height: 800,
    },
        {
      id: "side-table-perseus-side-table-4",
      url: "/images/collections/side-table-perseus-side-table-4.jpg",
      alt: "Perseus Side Table - Image 4",
      width: 1200,
      height: 800,
    },
        {
      id: "side-table-perseus-side-table-5",
      url: "/images/collections/side-table-perseus-side-table-5.jpg",
      alt: "Perseus Side Table - Image 5",
      width: 1200,
      height: 800,
    }
        ],
        materials: "Cast bronze with custom hammered patina",
        dimensions: [],
        order: 1,
      }
    ],
    order: 8,
  },
  {
    id: "9",
    title: "Lighting",
    slug: "lighting",
    heroImage: {
      id: "lighting-hero",
      url: "/images/collections/lighting-prometheus-wall-light-1.jpg",
      alt: "Lighting",
      width: 1200,
      height: 800,
    },
    products: [
      {
        id: "lighting-product-1",
        name: "Prometheus Wall Light",
        collectionName: "Warrior Collection",
        images: [
        {
      id: "lighting-prometheus-wall-light-1",
      url: "/images/collections/lighting-prometheus-wall-light-1.jpg",
      alt: "Prometheus Wall Light - Image 1",
      width: 1200,
      height: 800,
    },
        {
      id: "lighting-prometheus-wall-light-2",
      url: "/images/collections/lighting-prometheus-wall-light-2.jpg",
      alt: "Prometheus Wall Light - Image 2",
      width: 1200,
      height: 800,
    },
        {
      id: "lighting-prometheus-wall-light-3",
      url: "/images/collections/lighting-prometheus-wall-light-3.jpg",
      alt: "Prometheus Wall Light - Image 3",
      width: 1200,
      height: 800,
    },
        {
      id: "lighting-prometheus-wall-light-4",
      url: "/images/collections/lighting-prometheus-wall-light-4.jpg",
      alt: "Prometheus Wall Light - Image 4",
      width: 1200,
      height: 800,
    },
        {
      id: "lighting-prometheus-wall-light-5",
      url: "/images/collections/lighting-prometheus-wall-light-5.jpg",
      alt: "Prometheus Wall Light - Image 5",
      width: 1200,
      height: 800,
    }
        ],
        materials: "Brass base with sandblasted glass shade",
        dimensions: [],
        order: 1,
      }
    ],
    order: 9,
  }
];

const press: PressItem[] = [

];

// Export functions
export async function getProjects(): Promise<Project[]> {
  return projects.sort((a, b) => a.order - b.order);
}

export async function getFeaturedProjects(): Promise<Project[]> {
  return projects
    .filter((project) => project.featured)
    .sort((a, b) => a.order - b.order);
}

export async function getProjectBySlug(slug: string): Promise<Project | null> {
  return projects.find((project) => project.slug === slug) || null;
}

export async function getCollections(): Promise<Collection[]> {
  return collections.sort((a, b) => a.order - b.order);
}

export async function getCollectionBySlug(
  slug: string
): Promise<Collection | null> {
  return collections.find((collection) => collection.slug === slug) || null;
}

export async function getPress(): Promise<PressItem[]> {
  return press.sort(
    (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
  );
}
