import type { Metadata, Viewport } from "next";
import { Cormorant_Garamond, Inter } from "next/font/google";
import { AppWrapper } from "@/components/effects";
import { OrganizationSchema, LocalBusinessSchema } from "@/components/seo";
import "./globals.css";

const cormorant = Cormorant_Garamond({
  variable: "--font-cormorant",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  display: "swap",
  preload: true,
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500"],
  display: "swap",
  preload: true,
});

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#FAFAFA" },
    { media: "(prefers-color-scheme: dark)", color: "#111111" },
  ],
};

export const metadata: Metadata = {
  metadataBase: new URL("https://ozadesign.com"),

  title: {
    default: "OZA Design | Architecture & Interior Design",
    template: "%s | OZA Design",
  },

  description:
    "Award-winning architecture and interior design studio based in London and Istanbul. We create luxury residential spaces that transcend the ordinary.",

  keywords: [
    "interior design",
    "architecture",
    "luxury interiors",
    "residential design",
    "London interior designer",
    "Istanbul architect",
    "high-end interiors",
    "bespoke design",
    "furniture collection",
  ],

  authors: [{ name: "OZA Design", url: "https://ozadesign.com" }],
  creator: "OZA Design",
  publisher: "OZA Design",

  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },

  openGraph: {
    type: "website",
    locale: "en_GB",
    url: "https://ozadesign.com",
    siteName: "OZA Design",
    title: "OZA Design | Architecture & Interior Design",
    description:
      "Award-winning architecture and interior design studio creating luxury residential spaces in London and Istanbul.",
    // Images auto-generated by opengraph-image.tsx
  },

  twitter: {
    card: "summary_large_image",
    title: "OZA Design | Architecture & Interior Design",
    description:
      "Award-winning architecture and interior design studio.",
    // Images auto-generated by twitter-image.tsx
  },

  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  alternates: {
    canonical: "https://ozadesign.com",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${cormorant.variable} ${inter.variable}`}>
      <head>
        <OrganizationSchema />
        <LocalBusinessSchema />
      </head>
      <body>
        <AppWrapper>{children}</AppWrapper>
      </body>
    </html>
  );
}
